FROM node:20

WORKDIR /app

COPY package.json package-lock.json* ./
RUN npm install

COPY . .

CMD ["node", "index.js"]

COPY start.sh /usr/local/bin/start.sh
# ADD THESE TWO LINES FOR LINE ENDING CONVERSION:
RUN apt-get update && apt-get install -y dos2unix
RUN dos2unix /usr/local/bin/start.sh
# END OF ADDED LINES
RUN chmod +x /usr/local/bin/start.sh
ENTRYPOINT ["/usr/local/bin/start.sh"]